version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./mosquitto_data:/mosquitto/data:rw
      - ./mosquitto_data:/mosquitto/log:rw

  web-mqtt:
    image: emqx/mqttx-web
    container_name: mqtt5_web
    ports:
      - "8023:80"

# volumes for mapping data,config and log
volumes:
  config:
  mosquitto_data:

networks:
  default:
    name: mqtt5-network
